// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante.Models;

namespace Restaurante.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    [Migration("20220304233450_Adicionar classe Reserva")]
    partial class AdicionarclasseReserva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Restaurante.Models.Registo", b =>
                {
                    b.Property<int>("RegistoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("varchar(50)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int")
                        .HasColumnName("int(9)");

                    b.HasKey("RegistoID");

                    b.ToTable("Registo");
                });

            modelBuilder.Entity("Restaurante.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("varchar(50)");

                    b.Property<int>("NºdePessoas")
                        .HasColumnType("int")
                        .HasColumnName("int(2)");

                    b.Property<int>("RegistoID")
                        .HasColumnType("int");

                    b.Property<int>("Telefone")
                        .HasColumnType("int")
                        .HasColumnName("int(9)");

                    b.HasKey("ReservaID");

                    b.HasIndex("RegistoID");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Restaurante.Models.Reserva", b =>
                {
                    b.HasOne("Restaurante.Models.Registo", "Registo")
                        .WithMany()
                        .HasForeignKey("RegistoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registo");
                });
#pragma warning restore 612, 618
        }
    }
}
